### ISSUE TITLE
Features implemented

### ISSUE THREAD

**Issue by ezorfa** [Williano/Bona-Blog#10]
Hi @Williano !

Thankyou for open-sourcing this wonderful project. I am really interested in this project.

Do you know of any fully-finished medium-like clones open-sourced on GitHub? or Where do you derive the inspiration from when creating such a platform?

Do you have a reason why you have not chosen to implement with reactjs?

Thank-you!

**Comment by Williano** [comment]
Inspiration:
This project is based on the goal of improving my skills as a Software Engineer and the best way to improve is by building projects. I wanted to gain a deeper understanding of Django and Object-oriented programming in Python whiles I also contribute to the open-source community at the same time.

Why not use Rectjs?
The initial goal was to get a working project that people can use in version and later refactor to use a frontend framework.
So version 2 of the project will be either Reactjs or Vuejs. I am currently working on the mobile app version and will come to the version 2 later.
