### ISSUE TITLE
Article Image not changing remain to default

### ISSUE THREAD

**Issue by akhtersoyeb** [Williano/Bona-Blog#13]
Though I am providing image when creating an aritcle after publishing the article image remain to default. The image is not changing.

**Comment by Williano** [comment]
Let me check it and fix it. Thank you for bringing it to my attention.

**Comment by Williano** [comment]
I have fixed it. Please check and let me know if it works so that I can close this issue

**Comment by akhtersoyeb** [comment]
Works fine now.
